steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/gke-file-gateway/gke-file-gateway:latest', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/gke-file-gateway/gke-file-gateway:latest']
images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/gke-file-gateway/gke-file-gateway:latest'
options:
  logging: CLOUD_LOGGING_ONLY